brew unlink tadns && brew link tadns
brew unlink aften && brew link aften
brew unlink aom && brew link aom
brew unlink apr && brew link apr
brew unlink apr-util && brew link apr-util
brew unlink argon2 && brew link argon2
brew unlink arm-linux-gnueabihf-binutils && brew link arm-linux-gnueabihf-binutils
brew unlink asciinema && brew link asciinema
brew unlink aspell && brew link aspell
brew unlink autoconf && brew link autoconf
brew unlink automake && brew link automake
brew unlink aws-sam-cli && brew link aws-sam-cli
brew unlink awscli && brew link awscli
brew unlink azure-cli && brew link azure-cli
brew unlink bash && brew link bash
brew unlink bdw-gc && brew link bdw-gc
brew unlink berkeley-db && brew link berkeley-db
brew unlink bfg && brew link bfg
brew unlink binutils && brew link binutils
brew unlink brotli && brew link brotli
brew unlink c-ares && brew link c-ares
brew unlink cabal-install && brew link cabal-install
brew unlink cairo && brew link cairo
brew unlink circleci && brew link circleci
brew unlink clojure && brew link clojure
brew unlink cocoapods && brew link cocoapods
brew unlink cowsay && brew link cowsay
brew unlink ctop && brew link ctop
brew unlink curl && brew link curl
brew unlink cvs && brew link cvs
brew unlink dart && brew link dart
brew unlink dav1d && brew link dav1d
brew unlink docbook && brew link docbook
brew unlink docbook-xsl && brew link docbook-xsl
brew unlink ffmpeg && brew link ffmpeg
brew unlink flac && brew link flac
brew unlink fontconfig && brew link fontconfig
brew unlink freetds && brew link freetds
brew unlink freetype && brew link freetype
brew unlink frei0r && brew link frei0r
brew unlink fribidi && brew link fribidi
brew unlink gawk && brew link gawk
brew unlink gcc && brew link gcc
brew unlink gd && brew link gd
brew unlink gdb && brew link gdb
brew unlink gdbm && brew link gdbm
brew unlink gdk-pixbuf && brew link gdk-pixbuf
brew unlink geckodriver && brew link geckodriver
brew unlink gettext && brew link gettext
brew unlink gh && brew link gh
brew unlink ghc && brew link ghc
brew unlink ghostscript && brew link ghostscript
brew unlink giflib && brew link giflib
brew unlink git && brew link git
brew unlink git-lfs && brew link git-lfs
brew unlink git-secrets && brew link git-secrets
brew unlink glib && brew link glib
brew unlink gmp && brew link gmp
brew unlink gnu-getopt && brew link gnu-getopt
brew unlink gnu-sed && brew link gnu-sed
brew unlink gnupg && brew link gnupg
brew unlink gnutls && brew link gnutls
brew unlink gobject-introspection && brew link gobject-introspection
brew unlink golang-migrate && brew link golang-migrate
brew unlink goreman && brew link goreman
brew unlink graphite2 && brew link graphite2
brew unlink graphviz && brew link graphviz
brew unlink groff && brew link groff
brew unlink gsasl && brew link gsasl
brew unlink gts && brew link gts
brew unlink guile && brew link guile
brew unlink haproxy && brew link haproxy
brew unlink harfbuzz && brew link harfbuzz
brew unlink helm && brew link helm
brew unlink help2man && brew link help2man
brew unlink heroku && brew link heroku
brew unlink heroku-node && brew link heroku-node
brew unlink hub && brew link hub
brew unlink hugo && brew link hugo
brew unlink icu4c && brew link icu4c
brew unlink ideviceinstaller && brew link ideviceinstaller
brew unlink ilmbase && brew link ilmbase
brew unlink imagemagick && brew link imagemagick
brew unlink ios-deploy && brew link ios-deploy
brew unlink iproute2mac && brew link iproute2mac
brew unlink isl && brew link isl
brew unlink jack && brew link jack
brew unlink jansson && brew link jansson
brew unlink jasper && brew link jasper
brew unlink jemalloc && brew link jemalloc
brew unlink jpeg && brew link jpeg
brew unlink jq && brew link jq
brew unlink krb5 && brew link krb5
brew unlink kubectx && brew link kubectx
brew unlink kubernetes-cli && brew link kubernetes-cli
brew unlink lame && brew link lame
brew unlink leiningen && brew link leiningen
brew unlink leptonica && brew link leptonica
brew unlink libass && brew link libass
brew unlink libassuan && brew link libassuan
brew unlink libbluray && brew link libbluray
brew unlink libde265 && brew link libde265
brew unlink libev && brew link libev
brew unlink libevent && brew link libevent
brew unlink libffi && brew link libffi
brew unlink libgcrypt && brew link libgcrypt
brew unlink libgpg-error && brew link libgpg-error
brew unlink libheif && brew link libheif
brew unlink libidn2 && brew link libidn2
brew unlink libimobiledevice && brew link libimobiledevice
brew unlink libksba && brew link libksba
brew unlink liblqr && brew link liblqr
brew unlink libmetalink && brew link libmetalink
brew unlink libmpc && brew link libmpc
brew unlink libogg && brew link libogg
brew unlink libomp && brew link libomp
brew unlink libplist && brew link libplist
brew unlink libpng && brew link libpng
brew unlink libpq && brew link libpq
brew unlink libpthread-stubs && brew link libpthread-stubs
brew unlink librsvg && brew link librsvg
brew unlink libsamplerate && brew link libsamplerate
brew unlink libsndfile && brew link libsndfile
brew unlink libsodium && brew link libsodium
brew unlink libsoxr && brew link libsoxr
brew unlink libssh && brew link libssh
brew unlink libssh2 && brew link libssh2
brew unlink libtasn1 && brew link libtasn1
brew unlink libtiff && brew link libtiff
brew unlink libtool && brew link libtool
brew unlink libunistring && brew link libunistring
brew unlink libusb && brew link libusb
brew unlink libusbmuxd && brew link libusbmuxd
brew unlink libvidstab && brew link libvidstab
brew unlink libvorbis && brew link libvorbis
brew unlink libvpx && brew link libvpx
brew unlink libvterm && brew link libvterm
brew unlink libx11 && brew link libx11
brew unlink libxau && brew link libxau
brew unlink libxcb && brew link libxcb
brew unlink libxdmcp && brew link libxdmcp
brew unlink libxext && brew link libxext
brew unlink libxml2 && brew link libxml2
brew unlink libxmlsec1 && brew link libxmlsec1
brew unlink libxrender && brew link libxrender
brew unlink libzip && brew link libzip
brew unlink little-cms2 && brew link little-cms2
brew unlink llvm && brew link llvm
brew unlink lua && brew link lua
brew unlink lz4 && brew link lz4
brew unlink lzo && brew link lzo
brew unlink mailutils && brew link mailutils
brew unlink mas && brew link mas
brew unlink maven && brew link maven
brew unlink mecab && brew link mecab
brew unlink mecab-ipadic && brew link mecab-ipadic
brew unlink mercurial && brew link mercurial
brew unlink mpdecimal && brew link mpdecimal
brew unlink mpfr && brew link mpfr
brew unlink mysql-client && brew link mysql-client
brew unlink mysql@5.7 && brew link mysql@5.7
brew unlink nasm && brew link nasm
brew unlink ncurses && brew link ncurses
brew unlink nethack && brew link nethack
brew unlink netpbm && brew link netpbm
brew unlink nettle && brew link nettle
brew unlink nghttp2 && brew link nghttp2
brew unlink nginx && brew link nginx
brew unlink nmap && brew link nmap
brew unlink node && brew link node
brew unlink npth && brew link npth
brew unlink nspr && brew link nspr
brew unlink nss && brew link nss
brew unlink oath-toolkit && brew link oath-toolkit
brew unlink oniguruma && brew link oniguruma
brew unlink opencore-amr && brew link opencore-amr
brew unlink openexr && brew link openexr
brew unlink openjdk && brew link openjdk
brew unlink openjpeg && brew link openjpeg
brew unlink openldap && brew link openldap
brew unlink openssl@1.1 && brew link openssl@1.1
brew unlink opus && brew link opus
brew unlink p11-kit && brew link p11-kit
brew unlink pandoc && brew link pandoc
brew unlink pango && brew link pango
brew unlink pcre && brew link pcre
brew unlink pcre2 && brew link pcre2
brew unlink php@7.2 && brew link php@7.2
brew unlink pinentry && brew link pinentry
brew unlink pinentry-mac && brew link pinentry-mac
brew unlink pixman && brew link pixman
brew unlink pkg-config && brew link pkg-config
brew unlink plantuml && brew link plantuml
brew unlink poppler && brew link poppler
brew unlink popt && brew link popt
brew unlink postgresql && brew link postgresql
brew unlink psutils && brew link psutils
brew unlink python@3.7 && brew link python@3.7
brew unlink python@3.8 && brew link python@3.8
brew unlink python@3.9 && brew link python@3.9
brew unlink qemu && brew link qemu
brew unlink qt && brew link qt
brew unlink qt@5 && brew link qt@5
brew unlink rav1e && brew link rav1e
brew unlink rbenv && brew link rbenv
brew unlink readline && brew link readline
brew unlink redis && brew link redis
brew unlink rlwrap && brew link rlwrap
brew unlink rsync && brew link rsync
brew unlink rtmpdump && brew link rtmpdump
brew unlink rubberband && brew link rubberband
brew unlink ruby-build && brew link ruby-build
brew unlink sbcl && brew link sbcl
brew unlink sbt && brew link sbt
brew unlink sdl2 && brew link sdl2
brew unlink shared-mime-info && brew link shared-mime-info
brew unlink shellcheck && brew link shellcheck
brew unlink sl && brew link sl
brew unlink snappy && brew link snappy
brew unlink speex && brew link speex
brew unlink sqlite && brew link sqlite
brew unlink srt && brew link srt
brew unlink tcl-tk && brew link tcl-tk
brew unlink terraform && brew link terraform
brew unlink tesseract && brew link tesseract
brew unlink texinfo && brew link texinfo
brew unlink the_silver_searcher && brew link the_silver_searcher
brew unlink theora && brew link theora
brew unlink tidy-html5 && brew link tidy-html5
brew unlink tmux && brew link tmux
brew unlink translate-shell && brew link translate-shell
brew unlink tree && brew link tree
brew unlink uchardet && brew link uchardet
brew unlink unbound && brew link unbound
brew unlink unixodbc && brew link unixodbc
brew unlink utf8proc && brew link utf8proc
brew unlink vde && brew link vde
brew unlink webp && brew link webp
brew unlink wget && brew link wget
brew unlink whalebrew && brew link whalebrew
brew unlink wireguard-go && brew link wireguard-go
brew unlink wireguard-tools && brew link wireguard-tools
brew unlink x264 && brew link x264
brew unlink x265 && brew link x265
brew unlink xmlto && brew link xmlto
brew unlink xorgproto && brew link xorgproto
brew unlink xvid && brew link xvid
brew unlink xxhash && brew link xxhash
brew unlink xz && brew link xz
brew unlink yarn && brew link yarn
brew unlink yq && brew link yq
brew unlink zeromq && brew link zeromq
brew unlink zimg && brew link zimg
brew unlink zstd && brew link zstd
brew unlink chromedriver && brew link chromedriver
brew unlink docker && brew link docker
brew unlink gimp && brew link gimp
brew unlink google-cloud-sdk && brew link google-cloud-sdk
brew unlink keycastr && brew link keycastr
brew unlink latexit && brew link latexit
brew unlink ngrok && brew link ngrok
brew unlink vagrant && brew link vagrant
brew unlink vagrant-manager && brew link vagrant-manager
brew unlink virtualbox && brew link virtualbox
