#! /usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

exec docker run -it --rm \
     --privileged=true \
     --publish="127.0.0.1:50000:50000" \
     --env-file="${SCRIPT_DIR}/.env.db2" \
     --volume="db2-data:/database" \
     --name='db2-server' \
     'ibmcom/db2:11.5.5.0' \
     "$@"


# exec docker run -it -v "$(pwd)":/workdir -w /workdir \
#        --rm \
#        --env="LICENSE=accept" \
#        --env="DB2INST1_PASSWORD=Testing1234!" \
#        --env="SAMPLEDB=true" \
#        'ibmcom/db2:11.5.5.0' "$@"

#!/usr/bin/env whalebrew
#V image: ibmcom/db2:11.5.5.0
#V ports:
#V   - "50000:50000"
#V environment:
#V   - "LICENSE=accept"
#V   - "DB2INST1_PASSWORD=Testing1234!"
#V   - "SAMPLEDB=true"
#V volumes:
#V   - "db2-data:/database"
#V keep_container_user: true
#V container_name: db2-server
#V privileged: true
