#! /usr/bin/env bash
set -e -x

DOCKER_IMAGE=ibmcom/db2:11.5.5.0
docker run -it -v "$(pwd)":/workdir -w /workdir \
       --name='db2-server' \
       --rm \
       --privileged=true \
       --publish="50000:50000" \
       --env="LICENSE=accept" \
       --env="DB2INST1_PASSWORD=Testing1234!" \
       --env="SAMPLEDB=true" \
       --volume="db2-data:/database" \
       'ibmcom/db2:11.5.5.0' "$@"

#!/usr/bin/env whalebrew
#V image: ibmcom/db2:11.5.5.0
#V ports:
#V   - "50000:50000"
#V environment:
#V   - "LICENSE=accept"
#V   - "DB2INST1_PASSWORD=Testing1234!"
#V   - "SAMPLEDB=true"
#V volumes:
#V   - "db2-data:/database"
#V keep_container_user: true
#V container_name: db2-server
#V privileged: true
