#!/usr/bin/env bash
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cd ${SCRIPT_DIR}

export DYNAMO_ENDPOINT
export AWS_REGION

exec docker run -it --rm \
     --publish="8001:8001" \
     --expose="8001" \
     --name="dynamodb-admin" \
     --env-file="${SCRIPT_DIR}/.env.dynamodb-admin" \
     aaronshaf/dynamodb-admin \
     "$@"
