#! /usr/bin/env bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

function docker_run_errbit_rails_server () {
    exec docker run -it --rm \
         --privileged=true \
         --publish="127.0.0.1:8088:3000" \
         --expose="3000" \
         --name="errbit" \
         --volume "$(pwd):/workdir" \
         --env-file="${SCRIPT_DIR}/.env.errbit" \
         errbit/errbit:v0.9.0 \
         bundle exec rails server
}

function docker_exec_errbit_bundle () {
    exec docker exec -it errbit bundle "$@"
}

case "$1" in
    "")
        echo "Listen: http://localhostt:8088 | ${ERRBIT_ADMIN_EMAIL} / ${ERRBIT_ADMIN_PASSWORD}"
	docker_run_errbit_rails_server
        ;;
    "install")
	docker_exec_errbit_bundle install
        ;;
    "bootstrap")
	docker_exec_errbit_bundle exec rake errbit:bootstrap
        ;;
    *)
        exit 1
esac
