#!/usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

docker run -it --rm \
     --privileged=true \
     --publish="127.0.0.1:8080:8080"\
     --publish="127.0.0.1:50000:50000"\
     --expose="8080"\
     --expose="50000"\
     --workdir="/app" \
     --volume "$(pwd):/app" \
     --name="jenkins" \
     --volume="jenkins-data:/var/jenkins_home" \
     jenkins/jenkins:lts-jdk11 \
     "$@"
