#! /usr/bin/env bash
echo <<_WARNING_
Localstack hangs at startup if it mount the volume to /tmp/localstack.
Correctly should be permanent the volume, but it's not working well
due to a bug something maybe.

--volume "localstack-data:/tmp/localstack"
_WARNING_

set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

cd ${SCRIPT_DIR}

echo
echo -e "\033[33mThis is yellow\033[0m"

exec docker run -it --rm \
     --publish="127.0.0.1:4566:4566" \
     --publish="127.0.0.1:4571:4571" \
     --publish="127.0.0.1:8080:8080" \
     --expose="4566" \
     --expose="4571" \
     --expose="8080" \
     --workdir="/workdir" \
     --volume "$(pwd):/workdir" \
     --name="localstack" \
     --env-file="${SCRIPT_DIR}/.env.localstack" \
     localstack/localstack:0.12.6 \
     "$@"
