#! /usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

cd ${SCRIPT_DIR}
if [ "$#" -eq "0" ]
then
    args="server /data --console-address :9001"
else
    args=$@
fi

exec docker run -it --rm \
     --publish="127.0.0.1:9000:9000" \
     --publish="127.0.0.1:9001:9001" \
     --expose="9000" \
     --expose="9001" \
     --workdir="/workdir" \
     --volume "minio-data:/data" \
     minio/minio:RELEASE.2022-02-18T01-50-10Z.fips \
     $args
