#!/usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

exec docker run -it --rm \
     --privileged=true \
     --publish="127.0.0.1:1443:1443" \
     --expose="1443" \
     --workdir="/workdir" \
     --volume="$(pwd):/workdir" \
     --name="mssql" \
     --env-file="${SCRIPT_DIR}/.env.mssql" \
     mcr.microsoft.com/mssql/server:2017-latest \
     "$@"
