#!/usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

exec docker run -it --rm \
     --privileged=true \
     --publish="5432:5432" \
     --expose="5432" \
     --workdir="/workdir" \
     --volume "$(pwd):/workdir" \
     --volume "postgres-data:/var/lib/postgresql/data" \
     --name="postgres" \
     --env-file="${SCRIPT_DIR}/.env.postgres" \
     postgres:9.6-alpine \
     "$@"
