#!/usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

docker run -it --rm \
     --privileged=true \
     --workdir="/app" \
     --volume "$(pwd):/app" \
     --name="python-all" \
     sximada/python-all \
     "$@"
