#! /usr/bin/env bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

case "$1" in
    "")
	exec docker run -it --rm \
             --privileged=true \
             --publish="127.0.0.1:9000:9000" \
             --expose="9000" \
             --workdir="/workdir" \
             --volume "$(pwd):/workdir" \
             --volume "sentry-data:/var/lib/sentry/files" \
             --name="sentry" \
             --env-file="${SCRIPT_DIR}/.env.sentry" \
             sentry:9.1.2
	;;
    "cron")
	exec docker run -it --rm \
             --privileged=true \
             --workdir="/workdir" \
             --volume "$(pwd):/workdir" \
             --volume "sentry-data:/var/lib/sentry/files" \
             --name="sentry-cron" \
             --env-file="${SCRIPT_DIR}/.env.sentry" \
             sentry:9.1.2 \
             sentry run cron
	;;
    "worker")
	exec docker run -it --rm \
             --privileged=true \
             --workdir="/workdir" \
             --volume "$(pwd):/workdir" \
             --volume "sentry-data:/var/lib/sentry/files" \
             --name="sentry-worker" \
             --env-file="${SCRIPT_DIR}/.env.sentry" \
             sentry:9.1.2 \
             sentry run worker
	;;

    "upgrade")
	exec docker run -it --rm \
             --privileged=true \
             --publish="127.0.0.1:9000:9000" \
             --expose="9000" \
             --workdir="/workdir" \
             --volume "$(pwd):/workdir" \
             --volume "sentry-data:/var/lib/sentry/files" \
             --name="sentry-upgrade" \
             --env-file="${SCRIPT_DIR}/.env.sentry" \
             sentry:9.1.2 \
	     sentry upgrade
	;;
    *)
	shift
	exec docker run -it --rm \
             --privileged=true \
             --publish="127.0.0.1:9000:9000" \
             --expose="9000" \
             --workdir="/workdir" \
             --volume "$(pwd):/workdir" \
             --volume "sentry-data:/var/lib/sentry/files" \
             --name="sentry-cli" \
             --env-file="${SCRIPT_DIR}/.env.sentry" \
             sentry:9.1.2 \
	     sentry $@
	;;
esac
