#! /usr/bin/env bash
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

function docker_run () {
    exec docker run -it --rm \
	 --privileged=true \
	 --workdir="/workdir" \
	 --volume "$(pwd):/workdir" \
	 --volume "sentry-data:/var/lib/sentry/files" \
	 --name="sentry-cli" \
	 --env-file="${SCRIPT_DIR}/.env.sentry" \
	 sentry:9.1.2 \
	 $@
}

function docker_run_with_publish_ports () {
    exec docker run -it --rm \
	 --privileged=true \
	 --publish="127.0.0.1:9002:9000" \
	 --expose="9002" \
	 --workdir="/workdir" \
	 --volume "$(pwd):/workdir" \
	 --volume "sentry-data:/var/lib/sentry/files" \
	 --name="sentry" \
	 --env-file="${SCRIPT_DIR}/.env.sentry" \
	 sentry:9.1.2 \
	 $@
}

function docker_exec () {
    exec docker exec -it sentry $@
}

case "$1" in
    "")
	docker_run_with_publish_ports
	;;
    "cron")
	docker_exec sentry run $@
	;;
    "worker")
	docker_exec sentry run $@
	;;
    "init")
	# CREATE DATABASE sentry_local ENCODING='UTF8';
	docker_run sentry upgrade
	docker_run sentry createuser
	;;
    "createuser")
	docker_run sentry run createuser $@
	;;
    "exec")
	shift
	docker_exec bash $@
	;;
    "help")  # Display this message.
        echo "Hoka Script"
        echo
        grep -e '".*")' $0 | sed -e 's/[")]//g' | grep -v grep | sed -e 's/  #/\n\t/g'
        ;;
    *)
	docker_run bash $@
	;;
	;;
esac
