#! /usr/bin/env bash
# image: whalebrew/whalesay:latest
set -e -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)

exec docker run -it --rm \
     --name="whalesay" \
     --privileged=true \
     --env-file=${SCRIPT_DIR}/.env.whalesay \
     --volume "$(pwd):/workdir" \
     --workdir="/workdir" \
     whalebrew/whalesay:latest \
     "$@"
